import party.elias.Board
import party.elias.Move
import party.elias.TranspositionTable
import kotlin.math.min
import kotlin.random.Random
import kotlin.test.Test
import kotlin.test.assertEquals

class TTTests {

    @Test
    fun checkZobristRng() {
        val rng = Random(TranspositionTable.SEED)

        val totalCount = 64 * 12 + 1 + 4 + 8

        val generated = LongArray(totalCount)

        for (i in 0..<totalCount) {
            generated[i] = rng.nextLong()
        }

        fun evaluateMinimumLinearIndependence(
            maxDepth: Int,
            runningTotal: Long,
            prevLevelIndex: Int,
            depth: Int = 0
        ): Int {
            // minimum linear independence score (upper bound on size of smallest subset of numbers that xor to 0)
            var mlis = maxDepth

            for (i in 0..<prevLevelIndex) {
                val subTotal = runningTotal xor generated[i]
                if (subTotal == 0L) {
                    if (depth < mlis) {
                        mlis = depth
                        println("found new upper bound for mlis: $mlis")
                    }
                } else if (depth < maxDepth) {
                    mlis = min(mlis, evaluateMinimumLinearIndependence(mlis, subTotal, i, depth + 1))
                }
            }

            return mlis
        }

        val target = 3
        // checks if there are any <target> (or less) numbers in the first <totalCount> longs generated by the rng that xor together to 0
        assertEquals(target, evaluateMinimumLinearIndependence(target, 0L, totalCount))
    }

    @Test
    fun hashOfBoardGetsUpdatedCorrectly() {

        val position = Board.startPos()
        val startHash = position.zobristHash

        val m1 = Move.fromUci("f2f3", position)
        val m1State = position.doMove(m1)
        position.undoMove(m1, m1State)

        assertEquals(startHash, position.zobristHash)

        position.doMove(Move.fromUci("b1c3", position))
        position.doMove(Move.fromUci("c3b1", position))

        assertEquals(startHash, position.zobristHash)

    }
}